---
- name: Run network tasks
  ansible.builtin.import_tasks:
    file: 10_network.yml
  tags: network

- name: Run security group tasks
  ansible.builtin.import_tasks:
    file: 20_security_groups.yml
  tags: sg

- name: Create ec2 instance
  ansible.builtin.import_tasks:
    file: 30_ec2_instance.yml
  tags: ec2

- name: Run teardown tasks
  ansible.builtin.import_tasks:
    file: 40_teardown.yml
  tags: teardown

- name: Print Instance details
  ansible.builtin.import_tasks:
    file: 50_instance_details.yml
  tags: details
